/**
 * External CoachingProvider implementations (spec §15.5):
 * - `openai-compatible`: a remote OpenAI-compatible chat-completions endpoint,
 *   authenticated with a bearer key read from the environment.
 * - `local-model`: an on-machine model server (Ollama / LM Studio) exposing the
 *   same OpenAI-compatible `/v1/chat/completions` shape; no API key.
 *
 * Both are `external: true` and must only be reached through the CoachingGateway,
 * which enforces disabled-by-default, disclosure, redaction, preview, opt-in,
 * per-request cancellation, and external-advice marking (§15.5 steps 1–6).
 *
 * Privacy: only the single redacted prompt + its structural features are sent —
 * never a transcript (§15.5). The API key is passed in for the request only and
 * is never logged or persisted (§3.2).
 */
import type {
  CoachingCallOptions,
  CoachingProvider,
  GeneratedRemediation,
  RedactedPromptAnalysisInput,
  RedactedPromptPayload,
  RedactedRemediationInput,
  RedactedTaskClassificationInput,
  SemanticPromptAnalysis,
  TaskClassification,
} from "@agentlens/domain";
import { chatCompletion, extractJson, type ChatMessage } from "./chat.js";

/** Options shared by both external providers. */
export interface ExternalProviderOptions {
  endpoint: string;
  model: string;
  /** Bearer key (openai-compatible only); read from env by the caller. */
  apiKey?: string;
  /** Injected fetch (tests never touch the network). */
  fetchImpl?: typeof fetch;
  timeoutMs?: number;
}

const EXTERNAL_DISCLAIMER =
  "Generated by an external model. AgentLens sent only the redacted prompt and its " +
  "structural features — not your transcripts. Review this advice before acting on it.";

/** Build the user message sent to the model: redacted prompt + features only. */
function buildUserMessage(prompt: RedactedPromptPayload, task: string): string {
  const f = prompt.features;
  return [
    `Task: ${task}`,
    `Redacted prompt (sequence ${prompt.sequence}):`,
    `"${prompt.redactedContent}"`,
    `Structural features: imperativeVerbs=${f.imperativeVerbCount}, ` +
      `fileRefs=${f.fileReferenceCount}, vagueRefs=${f.ambiguousReferenceCount}, ` +
      `acceptanceCriteria=${f.referencesAcceptanceCriteria}, ` +
      `verification=${f.requestsVerification}, scopeMarkers=${f.hasScopeMarkers}, ` +
      `multiTask=${f.multipleIndependentTasks}, corrective=${f.appearsCorrective}, ` +
      `reversal=${f.appearsReversal}, complexity=${f.complexityScore.toFixed(2)}, ` +
      `length=${f.length}.`,
    `Respond ONLY with a single JSON object, no prose.`,
  ].join("\n");
}

/** Call the model for a given JSON schema instruction and parse the result. */
async function callModel(
  prompt: RedactedPromptPayload,
  schemaInstruction: string,
  opts: ExternalProviderOptions,
  id: string,
  options?: CoachingCallOptions,
): Promise<Record<string, unknown>> {
  const messages: ChatMessage[] = [
    {
      role: "system",
      content: `You are a coding-agent prompt coach. ${schemaInstruction} Respond ONLY with a single JSON object, no surrounding prose.`,
    },
    { role: "user", content: buildUserMessage(prompt, "Analyse the prompt.") },
  ];
  const content = await chatCompletion(messages, {
    endpoint: opts.endpoint,
    model: opts.model,
    apiKey: opts.apiKey,
    fetchImpl: opts.fetchImpl,
    timeoutMs: opts.timeoutMs,
    signal: options?.signal,
  });
  const parsed = extractJson(content);
  if (!parsed || typeof parsed !== "object") {
    throw new Error(`External provider ${id} returned unparseable JSON.`);
  }
  return parsed as Record<string, unknown>;
}

function asStringArray(v: unknown): string[] {
  return Array.isArray(v) ? v.filter((x): x is string => typeof x === "string") : [];
}

/** Build an external provider with the given id/key policy. */
function externalProvider(
  id: "openai-compatible" | "local-model",
  opts: ExternalProviderOptions,
): CoachingProvider {
  if (!opts.endpoint) {
    throw new Error(`External coaching provider ${id} requires an endpoint.`);
  }
  if (!opts.model) {
    throw new Error(`External coaching provider ${id} requires a model name.`);
  }
  return {
    id,
    external: true,
    async analysePrompt(
      input: RedactedPromptAnalysisInput,
      options?: CoachingCallOptions,
    ): Promise<SemanticPromptAnalysis> {
      const parsed = await callModel(
        input.prompt,
        'Return JSON: {"qualityNotes": string[], "suggestedMissing": string[]}.',
        opts,
        id,
        options,
      );
      return {
        generatedBy: "external",
        providerId: id,
        available: true,
        qualityNotes: asStringArray(parsed["qualityNotes"]),
        suggestedMissing: asStringArray(parsed["suggestedMissing"]),
        externalDisclaimer: EXTERNAL_DISCLAIMER,
      };
    },
    async classifyTask(
      input: RedactedTaskClassificationInput,
      options?: CoachingCallOptions,
    ): Promise<TaskClassification> {
      const parsed = await callModel(
        input.prompt,
        'Return JSON: {"taskType": string, "confidence": number, "rationale": string}.',
        opts,
        id,
        options,
      );
      const taskType = typeof parsed["taskType"] === "string" ? parsed["taskType"] : "unknown";
      const confidence =
        typeof parsed["confidence"] === "number"
          ? Math.max(0, Math.min(1, parsed["confidence"]))
          : 0;
      const rationale = typeof parsed["rationale"] === "string" ? parsed["rationale"] : "";
      return {
        generatedBy: "external",
        providerId: id,
        available: true,
        taskType,
        confidence,
        rationale,
        externalDisclaimer: EXTERNAL_DISCLAIMER,
      };
    },
    async generateRemediation(
      input: RedactedRemediationInput,
      options?: CoachingCallOptions,
    ): Promise<GeneratedRemediation> {
      const parsed = await callModel(
        input.prompt,
        'Return JSON: {"remediation": string, "steps": string[]}.',
        opts,
        id,
        options,
      );
      const remediation = typeof parsed["remediation"] === "string" ? parsed["remediation"] : "";
      return {
        generatedBy: "external",
        providerId: id,
        available: true,
        remediation,
        steps: asStringArray(parsed["steps"]),
        externalDisclaimer: EXTERNAL_DISCLAIMER,
      };
    },
  };
}

/** Remote OpenAI-compatible provider (bearer key from the environment). */
export function openAiCompatibleProvider(opts: ExternalProviderOptions): CoachingProvider {
  return externalProvider("openai-compatible", opts);
}

/** On-machine model provider (Ollama / LM Studio); no API key. */
export function localModelProvider(opts: ExternalProviderOptions): CoachingProvider {
  // local-model never sends an API key, even if one is passed.
  const localOpts: ExternalProviderOptions = {
    endpoint: opts.endpoint,
    model: opts.model,
    fetchImpl: opts.fetchImpl,
    timeoutMs: opts.timeoutMs,
  };
  return externalProvider("local-model", localOpts);
}
